#include <WiFi.h>
#include <PubSubClient.h>
#include "NetworkClassifier.h" // This is the file generated by micromlgen!

// --- Network & MQTT Configuration ---
const char* ssid = "YOUR_WIFI_SSID";
const char* password = "YOUR_WIFI_PASSWORD";
const char* mqtt_server = "broker.hivemq.com"; // Public testing broker
const int mqtt_port = 1883;

// --- MQTT Topics ---
const char* topic_stats = "esp32/network/stats";
const char* topic_alerts = "esp32/network/alerts";

WiFiClient espClient;
PubSubClient client(espClient);

// Instantiate your local machine learning model
Eloquent::ML::Port::NetworkClassifier classifier;

void setup_wifi() {
  delay(10);
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("\nWiFi connected");
}

void reconnect() {
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    String clientId = "ESP32Client-";
    clientId += String(random(0, 1000));
    
    if (client.connect(clientId.c_str())) {
      Serial.println("connected");
    } else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      delay(5000);
    }
  }
}

void setup() {
  Serial.begin(115200);
  setup_wifi();
  client.setServer(mqtt_server, mqtt_port);
}

void loop() {
  if (!client.connected()) {
    reconnect();
  }
  client.loop();

  // 1. Gather Network Features
  // In a real application, you track these metrics via WiFi events. 
  // Here, we simulate normal traffic.
  float time_interval = random(1000, 3000); 
  float packet_rate = random(1, 10);        
  float payload_size = random(64, 256);     
  float failed_auth = 0;                    

  // Occasionally simulate a Denial of Service (DoS) attack for testing
  if (random(0, 10) == 0) {
    time_interval = random(5, 20);
    packet_rate = random(150, 250);
  }

  // 2. Prepare the feature array exactly as trained in Python
  // Order matters: time_interval, packet_rate, payload_size, failed_auth
  float features[4] = { time_interval, packet_rate, payload_size, failed_auth };


  // 3. Run AI Inference locally on the ESP32
  int class_index = classifier.predict(features);
  
  // Map the integer back to the string label (alphabetical order)
  String labels[4] = {"Attack_BruteForce", "Attack_DoS", "Attack_Payload", "Normal"};
  String prediction = labels[class_index];
  
  Serial.print("Traffic classified as: ");
  Serial.println(prediction);

  // 4. Create JSON string for dashboard stats
  String statsPayload = "{\"packet_rate\":" + String(packet_rate) + 
                        ", \"payload_size\":" + String(payload_size) + "}";
  client.publish(topic_stats, statsPayload.c_str());

  // 5. Alert Generation based on AI prediction
  // Our Python model was trained to output "Normal", "Attack_DoS", "Attack_Payload", etc.
  if (prediction != "Normal") {
    String alertPayload = "CRITICAL: AI detected " + prediction + " ! Rate: " + String(packet_rate);
    Serial.println(alertPayload);
    client.publish(topic_alerts, alertPayload.c_str());
  }

  delay(2000); // Wait 2 seconds before next inference check
}